# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

base:
  start_date: 2019-01-01 00:00
  end_date: 2019-01-06 00:00
  time_step: 1h
  save_frequency_hours: null
  learning_mode: True

  learning_config:
    continue_learning: False
    trained_policies_save_path: null
    max_bid_price: 100
    algorithm: matd3
    learning_rate: 0.001
    training_episodes: 50
    episodes_collecting_initial_experience: 5
    train_freq: 24h
    gradient_steps: -1
    batch_size: 256
    gamma: 0.99
    device: cpu
    noise_sigma: 0.1
    noise_scale: 1
    noise_dt: 1
    validation_episodes_interval: 5
    early_stopping_steps: 10
    early_stopping_threshold: 0.05

  markets_config:
    DAM:
      start_date: 2019-01-01 00:00
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 24
          first_delivery: 24h
      opening_frequency: 24h
      opening_duration: 20h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

    redispatch:
      start_date: 2019-01-01 21:00
      operator: network_operator
      product_type: energy
      products:
        - duration: 1h
          count: 24
          first_delivery: 3h
      opening_frequency: 24h
      opening_duration: 2h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: redispatch
      additional_fields:
        - node
        - min_power
        - max_power
      param_dict:
        network_path: .
        solver: glpk
        payment_mechanism: pay_as_bid
        backup_marginal_cost: 10000
