tiny:
  start_date: 2019-01-01 00:00
  end_date: 2019-01-05 00:00
  save_frequency_hours: null  
  time_step: 1h
  learning_mode: true
  learning_config:
    algorithm: ppo
    continue_learning: false
    device: cpu
    gradient_steps: 10
    learning_rate: 0.0003
    max_bid_price: 100
    trained_policies_save_path: null
    training_episodes: 100
    validation_episodes_interval: 10
    matd3:
      actor_architecture: mlp
      batch_size: 64
      episodes_collecting_initial_experience: 3
      gamma: 0.99
      noise_dt: 1
      noise_scale: 1
      noise_sigma: 0.1
      train_freq: 24h
  markets_config:
    EOM:
      market_mechanism: pay_as_clear
      maximum_bid_price: 3000
      maximum_bid_volume: 100000
      minimum_bid_price: -500
      opening_duration: 1h
      opening_frequency: 1h
      operator: EOM_operator
      price_unit: EUR/MWh
      product_type: energy
      products:
      - count: 1
        duration: 1h
        first_delivery: 1h
      volume_unit: MWh


base:
  start_date: 2019-03-01 00:00
  end_date: 2019-03-31 00:00
  time_step: 1h
  learning_mode: true
  save_frequency_hours: null

  learning_config:
    algorithm: matd3
    continue_learning: false
    device: cpu
    gradient_steps: -1
    learning_rate: 0.001
    max_bid_price: 100
    trained_policies_save_path: null
    training_episodes: 100
    validation_episodes_interval: 10
    learning_mode: true
    matd3:
      actor_architecture: mlp
      batch_size: 64
      episodes_collecting_initial_experience: 3
      gamma: 0.99
      noise_dt: 1
      noise_scale: 1
      noise_sigma: 0.1
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2019-03-01 00:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear




tiny_ppo:
  save_frequency_hours: null
  start_date: 2019-03-01 00:00
  time_step: 1h
  end_date: 2019-03-31 00:00
  learning_mode: true
  learning_config:
    algorithm: ppo
    continue_learning: false
    device: cpu
    gradient_steps: 10
    learning_rate: 0.0003
    max_bid_price: 100
    trained_policies_save_path: null
    training_episodes: 100
    validation_episodes_interval: 10
    matd3:
      actor_architecture: mlp
      batch_size: 64
      episodes_collecting_initial_experience: 3
      gamma: 0.99
      noise_dt: 1
      noise_scale: 1
      noise_sigma: 0.1
      train_freq: 24h
    ppo:
      actor_architecture: dist
      batch_size: 11
      clip_ratio: 0.05
      entropy_coef: 0.005
      gae_lambda: 0.95
      gamma: 0.99
      max_grad_norm: 0.3
      train_freq: 33h
      vf_coef: 0.75
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2019-03-01 00:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear


base_ppo_linear:
  start_date: 2019-03-01 00:00
  end_date: 2019-03-31 00:00
  time_step: 1h
  save_frequency_hours: null
  learning_mode: true
  learning_config:
    algorithm: ppo
    continue_learning: false
    device: cpu
    gradient_steps: 10
    learning_rate: 0.0003
    validation_episodes_interval: 5 # after how many episodes the validation starts and the policy is updated
    training_episodes: 100
    validation_episodes_interval: 10
    max_bid_price: 100
    matd3:
      actor_architecture: mlp
      batch_size: 64
      episodes_collecting_initial_experience: 3
      gamma: 0.99
      noise_dt: 1
      noise_scale: 1
      noise_sigma: 0.1
      train_freq: 24h
    ppo:
      actor_architecture: dist
      train_freq: 33h # how often write_to_learning_role gets called
      gamma: 0.99 # Discount factor for future rewards
      clip_ratio: 0.05  # Clipping parameter for policy updates
      vf_coef: 0.75  # Value function coefficient in the loss function
      entropy_coef: 0.005  # Entropy coefficient for exploration
      max_grad_norm: 0.3  # Gradient clipping value
      gae_lambda: 0.95  # GAE lambda for advantage estimation
      batch_size: 11  # Batch size for each update, if mini-batch approach is used (currently not implemented)

      actor_learning_rate: 0.0003 #allow for separate learning rates of actor and critic
      critic_learning_rate: 0.0003
      scheduler_type: linear
      actor_lr_scheduler_params:
        start_factor: 1 
        end_factor: 0.1   #final learning rate = 0.1 * initial learning rate
        total_iters: 500
      critic_lr_scheduler_params:
        start_factor: 1 
        end_factor: 0.1
        total_iters: 500 

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

base_lstm:
  start_date: 2019-03-01 00:00
  end_date: 2019-03-31 00:00
  time_step: 1h
  save_frequency_hours: null
  learning_mode: True

  learning_config:
    continue_learning: False
    trained_policies_save_path: null
    max_bid_price: 100
    algorithm: matd3
    actor_architecture: lstm
    learning_rate: 0.001
    training_episodes: 50
    episodes_collecting_initial_experience: 5
    train_freq: 24h
    gradient_steps: -1
    batch_size: 256
    gamma: 0.99
    device: cpu
    noise_sigma: 0.1
    noise_scale: 1
    noise_dt: 1
    validation_episodes_interval: 5
    early_stopping_steps: 10
    early_stopping_threshold: 0.05

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2019-01-01 00:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh

