dsu_1:
  name: Steelplant_DE6_hamburg
  plant_type: electrolyser_shaftFurnace_EAF
  location: 
  bidding_energy: naive_da_steel_plant
  unit_operator: dsm_operator_1
  objective: minimize_marginal_cost
  technology:
    electrolyser:
      - max_power: 100
      - min_power: 20
      - ramp_up: 10
      - ramp_down: 10
      - min_operating_time: 1
      - min_down_time: 0.5
      - downtime_hot_start: 0.25
      - downtime_warm_start: 0.1
      - efficiency: 0.75
      - compressor_power: 5
    shaft_furnace:
      - ramp_up: 50
      - ramp_down: 50
      - min_operating_time: 1
      - min_down_time: 0.5
      - efficiency: 0.85
      - compressor_power: 500
      - max_iron_ore_throughput: 0.99
      - dri_production_efficiency: TRUE
      - natural_gas_inlet: 300
      - max_natural_gas_input: TRUE
      - hydrogen_inlet: 200
    electric_arc_furnace:
      - max_power: 200
      - ramp_up: 40
      - ramp_down: 40
      - min_operating_time: 1
      - min_down_time: 0.5
      - efficiency: 0.8
      - max_dri_input: 400

dsu_2:
  name: Steelplant_DE5_duisburg
  plant_type: electrolyser
  location: 
  bidding_energy: naive_da_electrolyser_plant
  unit_operator: dsm_operator_s
  objective: minimize_marginal_cost
  technology:
    electrolyser:
    ..
    ..
    ...