# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

base:
  start_date: 2019-03-01 00:00
  end_date: 2019-04-01 00:00
  time_step: 1h
  save_frequency_hours: null
  learning_mode: True

  learning_config:
    continue_learning: False
    trained_policies_save_path: null
    max_bid_price: 100
    algorithm: matd3
    actor_architecture: mlp
    learning_rate: 0.001
    training_episodes: 100
    episodes_collecting_initial_experience: 3
    train_freq: 24h
    gradient_steps: 1
    batch_size: 256
    gamma: 0.99
    device: cpu
    noise_sigma: 0.1
    noise_scale: 1
    noise_dt: 1
    validation_episodes_interval: 5
    early_stopping_steps: 10
    early_stopping_threshold: 0.05

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear


base_ppo:
  start_date: 2019-03-01 00:00
  end_date: 2019-04-01 00:00
  time_step: 1h
  save_frequency_hours: null
  learning_mode: True

  learning_config:
    continue_learning: False
    trained_policies_save_path: null
    max_bid_price: 100
    algorithm: ppo
    device: cpu
    learning_rate: 0.0003 # default learning rate
    validation_episodes_interval: 10 # after how many episodes the validation starts and the policy is updated
    training_episodes: 100
    gradient_steps: 10
    matd3:
      actor_architecture: mlp
      train_freq: 24h # how often write_to_learning_role gets called
      episodes_collecting_initial_experience: 3
      batch_size: 64
      gamma: 0.99
      noise_sigma: 0.1
      noise_scale: 1
      noise_dt: 1
    ppo: 
      actor_architecture: dist
      train_freq: 33h # how often write_to_learning_role gets called
      gamma: 0.99 # Discount factor for future rewards
      clip_ratio: 0.1  # Clipping parameter for policy updates
      vf_coef: 0.75  # Value function coefficient in the loss function
      entropy_coef: 0.01  # Entropy coefficient for exploration
      max_grad_norm: 0.3  # Gradient clipping value
      gae_lambda: 0.95  # GAE lambda for advantage estimation
      batch_size: 11  # Batch size for each update, if mini-batch approach is used (currently not implemented)
      
      actor_learning_rate: 0.0003 #allow for separate learning rates of actor and critic
      critic_learning_rate: 0.0003
      scheduler_type: none
      actor_lr_scheduler_params:
        step_size: 30 # Number of epochs between learning rate decays
        gamma: 0.95   # 1 - decay in learning rate 
      critic_lr_scheduler_params:
        step_size: 30 
        gamma: 0.95  

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear


base_lstm:
  start_date: 2019-03-01 00:00
  end_date: 2019-04-01 00:00
  time_step: 1h
  save_frequency_hours: null
  learning_mode: True

  learning_config:
    continue_learning: False
    trained_policies_save_path: null
    max_bid_price: 100
    algorithm: matd3
    actor_architecture: lstm
    learning_rate: 0.001
    training_episodes: 100
    episodes_collecting_initial_experience: 3
    train_freq: 24h
    gradient_steps: 1
    batch_size: 256
    gamma: 0.99
    device: cpu
    noise_sigma: 0.1
    noise_scale: 1
    noise_dt: 1
    validation_episodes_interval: 5
    early_stopping_steps: 10
    early_stopping_threshold: 0.05

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear
