# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

dam_with_uc_clearing_rl:
  sim_id: run_all
  start_date: 2019-03-01 23:00
  end_date: 2019-03-02 23:00
  time_step: 1h
  save_frequency_hours: Null
  learning_mode: False

  learning_config:
    observation_dimension: 50
    action_dimension: 24
    continue_learning: False
    trained_policies_save_path: learned_strategies/run-all/best_avg_reward
    max_bid_price: 100
    algorithm: matd3
    learning_rate: 0.001
    training_episodes: 500
    episodes_collecting_initial_experience: 2
    train_freq: 24
    gradient_steps: 2
    batch_size: 16
    gamma: 0.7
    device: cpu`
    noise_sigma: 0.1
    noise_scale: 1
    noise_dt: 1
    validation_episodes_interval: 5

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 24
          first_delivery: 1h
      opening_frequency: 24h
      opening_duration: 24h
      volume_unit: MWh
      maximum_bid_volume: null
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: uc_clearing

dam_with_uc_clearing:
  start_date: 2019-03-01 00:00
  end_date: 2019-03-05 00:00
  time_step: 1h
  save_frequency_hours: Null

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 24
          first_delivery: 1h
      opening_frequency: 24h
      opening_duration: 24h
      volume_unit: MWh
      maximum_bid_volume: null
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: uc_clearing
